//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS_CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lead
    {
        public int Id { get; set; }
        public string Razon_Social { get; set; }
        public string CUIT { get; set; }
        public string Telefono_Razon_Social { get; set; }
        public string Email_Razon_Social { get; set; }
        public string Nombre_Contacto { get; set; }
        public string Cargo_Contacto { get; set; }
        public string Telefono_Contacto { get; set; }
        public string Telefono2_Contacto { get; set; }
        public string Email_Contacto { get; set; }
        public string Email2_Contacto { get; set; }
        public string Informacion_Fiscal { get; set; }
        public string Provincia { get; set; }
        public string Localidad { get; set; }
    }
}
