//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS_CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lineas_Asiento
    {
        public int Id { get; set; }
        public Nullable<int> Asiento_Id { get; set; }
        public Nullable<int> Cuenta_Id { get; set; }
        public string Concepto { get; set; }
        public Nullable<decimal> Debe { get; set; }
        public Nullable<decimal> Haber { get; set; }

        public decimal Saldo { get { return Debe.Value - Haber.Value; } }
    
        public virtual Plan_Cuentas Plan_Cuentas { get; set; }
        public virtual Asiento Asiento { get; set; }
    }
}
