//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS_CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoGasto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoGasto()
        {
            this.GastosFijos = new HashSet<GastosFijo>();
            this.GastosVariables = new HashSet<GastosVariable>();
        }
    
        public int Id { get; set; }
        public string Acronimo { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Cuenta_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GastosFijo> GastosFijos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GastosVariable> GastosVariables { get; set; }
        public virtual Plan_Cuentas Plan_Cuentas { get; set; }
    }
}
