//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS_CRM
{
    using System;
    using System.Collections.Generic;
        using System.ComponentModel.DataAnnotations;

    public partial class AcuardosComerciale
    {
        public int Id { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public Nullable<decimal> ValorHora { get; set; }
        public Nullable<int> HorasVendidas { get; set; }
        public Nullable<decimal> ImporteTotal { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<bool> IsActiva { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
