//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS_CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificacionHora
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public Nullable<int> ComprobanteId { get; set; }
        public Nullable<decimal> HorasACertificar { get; set; }
        public Nullable<decimal> HorasCertificadas { get; set; }
        public Nullable<decimal> Saldo { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Comprobante Comprobante { get; set; }
    }
}
