//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS_CRM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AS_CRMEntities : DbContext
    {
        public AS_CRMEntities()
            : base("name=AS_CRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Lead> Leads { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Comprobante> Comprobantes { get; set; }
        public virtual DbSet<GastosFijo> GastosFijos { get; set; }
        public virtual DbSet<GastosVariable> GastosVariables { get; set; }
        public virtual DbSet<TipoGasto> TipoGastoes { get; set; }
        public virtual DbSet<TiposComprobante> TiposComprobantes { get; set; }
        public virtual DbSet<AcuardosComerciale> AcuardosComerciales { get; set; }
        public virtual DbSet<CertificacionHora> CertificacionHoras { get; set; }
        public virtual DbSet<Plan_Cuentas> Plan_Cuentas { get; set; }
        public virtual DbSet<Lineas_Asiento> Lineas_Asiento { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<ItemMenuSecurity> ItemMenuSecurities { get; set; }
        public virtual DbSet<MenuSecurity> MenuSecurities { get; set; }
        public virtual DbSet<PEstado> PEstados { get; set; }
        public virtual DbSet<PObjetivo> PObjetivos { get; set; }
        public virtual DbSet<Proyecto> Proyectos { get; set; }
        public virtual DbSet<PSprint> PSprints { get; set; }
        public virtual DbSet<PTarea> PTareas { get; set; }
        public virtual DbSet<Asiento> Asientos { get; set; }
        public virtual DbSet<PParteHora> PParteHoras { get; set; }
        public virtual DbSet<PFilesTarea> PFilesTareas { get; set; }
        public virtual DbSet<PPrioridade> PPrioridades { get; set; }
        public virtual DbSet<PTareasComentario> PTareasComentarios { get; set; }
    }
}
