//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS_CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFilesTarea
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Extencion { get; set; }
        public string LinkName { get; set; }
        public Nullable<int> Tarea_Id { get; set; }
    
        public virtual PTarea PTarea { get; set; }
    }
}
